# Generated by Django 3.1.1 on 2021-04-13 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='legal_number',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='department',
            name='admin',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
        migrations.AddField(
            model_name='department',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.department'),
        ),
        migrations.AlterField(
            model_name='company',
            name='create_user',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='update_user',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='create_user',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='update_user',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='create_user',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='update_user',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
